Repository SOPT-Joint-Seminar-Twitter/Twitter-AOS, pull requests merged in 2022-05, with the labels that each got.

#7 [FEAT] #4 implement home
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  README.md
  app/build.gradle
  app/src/main/java/com/join_seminar/twitter/data/TwitData.kt
  app/src/main/java/com/join_seminar/twitter/ui/base/BaseActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/base/BaseFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeTabAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/InfoFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/MediaFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/MindFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/ReplyFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitFragment.kt
  app/src/main/java/com/join_seminar/twitter/util/BindingAdapter.kt
  app/src/main/res/circle_border_black_3.xml
  app/src/main/res/drawable-hdpi/rectangle_border_gray_radius_18.xml
  app/src/main/res/drawable-hdpi/selector_retwit_gray_to_green.xml
  app/src/main/res/drawable-hdpi/selector_text_gray_to_green.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_media.xml
  app/src/main/res/layout/fragment_mind.xml
  app/src/main/res/layout/fragment_reply.xml
  app/src/main/res/layout/fragment_twit.xml
  app/src/main/res/layout/item_twit_list.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🌚혜빈🌚, 🐥FEAT🐥

#6 #3 [FEAT] Write Activity 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/join_seminar/twitter/ui/util/BindingAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/write/WriteActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/write/WriteAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/write/WriteViewModel.kt
  app/src/main/res/drawable-hdpi/android_ic_earth.png
  app/src/main/res/drawable-hdpi/android_ic_x.png
  app/src/main/res/drawable-mdpi/android_ic_earth.png
  app/src/main/res/drawable-mdpi/android_ic_x.png
  app/src/main/res/drawable-xhdpi/android_ic_earth.png
  app/src/main/res/drawable-xhdpi/android_ic_x.png
  app/src/main/res/drawable-xxhdpi/android_ic_earth.png
  app/src/main/res/drawable-xxhdpi/android_ic_x.png
  app/src/main/res/drawable-xxxhdpi/android_ic_earth.png
  app/src/main/res/drawable-xxxhdpi/android_ic_x.png
  app/src/main/res/drawable/write_button_selector.xml
  app/src/main/res/drawable/write_cursor_color.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/write_recyclerview_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🌞원용🌞, 🐥FEAT🐥

#12 [FEAT] #8 implement write
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/join_seminar/twitter/data/WriteData.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/adapter/TwitAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/write/WriteActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/write/adapter/WriteAdapter.kt
  app/src/main/java/com/join_seminar/twitter/util/BindingAdapter.kt
  app/src/main/res/drawable-hdpi/ic_delete.png
  app/src/main/res/drawable-hdpi/ic_earth.png
  app/src/main/res/drawable-mdpi/ic_delete.png
  app/src/main/res/drawable-mdpi/ic_earth.png
  app/src/main/res/drawable-xhdpi/ic_delete.png
  app/src/main/res/drawable-xhdpi/ic_earth.png
  app/src/main/res/drawable-xxhdpi/ic_delete.png
  app/src/main/res/drawable-xxhdpi/ic_earth.png
  app/src/main/res/drawable-xxxhdpi/ic_delete.png
  app/src/main/res/drawable-xxxhdpi/ic_earth.png
  app/src/main/res/drawable/selector_rectangle_blue2_to_blue1.xml
  app/src/main/res/drawable/selector_text_gray_to_white.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/item_write_img_list.xml
  app/src/main/res/values/strings.xml
Labels: 🌚혜빈🌚, 🐥FEAT🐥

#13 [Modify] #8 - 패키징 수정
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/adapter/HomeTabAdapter.kt
Labels: 🌚혜빈🌚, 🛠MODIFY🛠

#15 #14 [DOCS] 리드미 수정
  README.md
  app/src/main/java/com/join_seminar/twitter/ui/main/BindingAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/util/BindingAdapter.kt
Labels: 🌚혜빈🌚

#11 [FEAT] #10 wrapper class , retrofit builder 추가
  app/build.gradle
  app/src/main/java/com/join_seminar/twitter/ui/data/ApiService.kt
  app/src/main/java/com/join_seminar/twitter/ui/data/RetrofitBuilder.kt
  app/src/main/java/com/join_seminar/twitter/ui/data/WrapperClass.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitAdapter.kt
Labels: 🌞원용🌞, 🐥FEAT🐥

#18 Feat/17 user check server connection
  .gitignore
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/join_seminar/twitter/data/api/ApiService.kt
  app/src/main/java/com/join_seminar/twitter/data/api/ServiceCreator.kt
  app/src/main/java/com/join_seminar/twitter/data/response/ResponseUserInfoData.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/HomeActivity.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
Labels: 🌚혜빈🌚, 🐥FEAT🐥

#20 [CHORE] #1 - header 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/join_seminar/twitter/ui/data/RetrofitBuilder.kt
Labels: 🌚혜빈🌚, 💻CHORE💻

#25 Feat/19 twit list server connection
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/join_seminar/twitter/data/api/ApiService.kt
  app/src/main/java/com/join_seminar/twitter/data/response/ResponseTwitList.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/TwitFragment.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/adapter/TwitAdapter.kt
  app/src/main/java/com/join_seminar/twitter/ui/main/viewmodel/HomeViewModel.kt
  app/src/main/java/com/join_seminar/twitter/util/BindingAdapter.kt
  app/src/main/res/layout/item_twit_list.xml
Labels: 🌚혜빈🌚, 🐥FEAT🐥
